#!/usr/bin/python

import serial, sys, glob

if len(sys.argv) >= 2:
    ser = serial.Serial(sys.argv[1])
else:
    for port in glob.glob('/dev/ttyACM*'):
        try:
            ser = serial.Serial(port, 9600)
        except Exception:
            pass # Fail
        else:
            break
    else:
        sys.exit("No ports found")



txt = raw_input("> ")
ser.write('\x03'+txt+'\n\n\n')
